global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: adserve
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:28080"]
        labels: {service: adserve}
  - job_name: beacons
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:28081"]
        labels: {service: beacons}
