"""Builds NUMBERS_LEDGER.md from results/*.jsonl so no figure is copied by hand.
Run: python3 scripts/ledger.py"""
import json, os, statistics
from collections import defaultdict

R = "results"

def rows(f):
    p = os.path.join(R, f)
    return [json.loads(l) for l in open(p)] if os.path.exists(p) else []

def machine(o):
    m = o.get("machine", {})
    return f"{m.get('cpu','?')}, {m.get('cores','?')} cores, {m.get('memory_gb','?')} GB, low power mode {m.get('low_power_mode','?')}"

out = ["# Numbers ledger", "",
       "Generated by `scripts/ledger.py` from `results/*.jsonl`. Every row names its file. All runs are on",
       "one laptop with the load generator (where there is one) on the same machine, which was shared",
       "with another project's benchmarks; the two took turns through a lock (`scripts/lib.sh`).",
       "`results/archive/` holds superseded runs and is never quoted.", ""]

# exp1 / exp6 / exp9: bursts
def burst_table(file, title, note):
    rs = rows(file)
    if not rs: return
    out.extend([f"## {title}", "", note, "",
                f"File `results/{file}`. Machine: {machine(rs[0])}. Burst: N requests in 2 s, gamma arrival (k=2, theta 0.4 s), all LIVE, fresh simulated viewers per repeat, real ad-break contexts from iPinYou 2013-06-11. Latency is from each request's intended send time (open loop).", "",
                "| Label | N in 2 s | Offered peak /s | Repeat | OK | Error rate | p50 ms | p99 ms | p99.9 ms | Ads per pod | Load avg before |",
                "|---|---|---|---|---|---|---|---|---|---|---|"])
    for o in rs:
        L = o["live"]
        out.append(f"| {o['label']} | {o['burst_requests']:,} | {o['offered_peak_per_s']:,.0f} | {o['repeat']} | {L['ok']:,} | {L['error_rate']:.4f} | {L['p50_ms']:.2f} | {L['p99_ms']:.2f} | {L['p999_ms']:.2f} | {L['mean_ads_per_pod']:.2f} | {o.get('load_avg_before_burst','').strip('{} ').split(' ')[0]} |")
    out.append("")
    notes = sorted({(o['label'], o.get('note', '')) for o in rs if o.get('note')})
    for l, n in notes: out.append(f"- `{l}`: {n}")
    if notes: out.append("")

burst_table("exp1_burst.jsonl", "Experiment 1: live-break burst, AdServe against a synchronous database write",
            "`adserve` logs each decision to Kafka without waiting; `legacy_sync_write` inserts it into Postgres before responding.")

# exp2
rs = rows("exp2_pacing.jsonl")
if rs:
    out.extend(["## Experiment 2: pacing over one real day", "",
                f"File `results/exp2_pacing.jsonl` (per campaign: `exp2_pacing_campaigns.jsonl`). Machine: {machine(rs[0])}. The full replay day (1,745,722 ad breaks) through the real decision engine on a simulated fleet of 8 nodes that sync spend every 10 simulated seconds; 55 campaigns, budgets are each creative's real spend that day; pacers plan on the previous day's traffic and are scored against the replay day's own eligible traffic. Deterministic: one run per configuration.", "",
                "| Pacer | Per-node allowance | Delivered (all budgets) | Mean abs landing error | Within 5% of budget | Overspent campaigns | Aggregate overspend | Max overspend | Exhausted before 23:00 | Mean exhaustion hour | Mean RMSE vs plan |",
                "|---|---|---|---|---|---|---|---|---|---|---|"])
    for o in rs:
        eh = o['mean_exhaustion_hour']
        out.append(f"| {o['pacer']} | {'yes' if o['allowance_split'] else 'no'} | {o['aggregate_delivered_fraction']:.3f} | {o['mean_abs_landing_error']:.3f} | {o['campaigns_within_5pct_of_budget']} of {o['campaigns']} | {o['campaigns_overspent']} | {o['aggregate_overspend_fraction']*100:.2f}% | {o['max_overspend_fraction']*100:.1f}% | {o['campaigns_exhausted_before_hour_23']} | {'-' if eh is None else f'{eh:.1f}'} | {o['mean_rmse_vs_plan']:.3f} |")
    out.append("")

# exp3
rs = rows("exp3_caps.jsonl")
if rs:
    out.extend(["## Experiment 3: frequency caps under duplicated, late and lost beacons", "",
                f"File `results/exp3_caps.jsonl`. Machine: {machine(rs[0])}; Redis 7.4 in Docker on the same machine. {rs[0]['traffic']}. Beacons lost 1%, late (5 to 60 min) 3%, otherwise 0.5 to 30 s. One run per cell.", "",
                "| Counter design | Duplicate prob | Impressions served | Duplicated deliveries | Cap violations | Ad-load violations | Wrongly refused | Counter drift |",
                "|---|---|---|---|---|---|---|---|"])
    for o in rs:
        out.append(f"| {o['mode']} | {o['duplicate_probability']:.2f} | {o['impressions_served']:,} | {o['duplicated_beacon_deliveries']:,} | {o['cap_violations']} | {o['ad_load_violations']} | {o['wrongly_refused']:,} | {o['counter_drift_pct']:+.2f}% |")
    tot = sum(o['duplicated_beacon_deliveries'] for o in rs if o['mode'] == 'idempotent')
    viol = sum(o['cap_violations'] + o['ad_load_violations'] for o in rs if o['mode'] == 'idempotent')
    out.extend(["", f"Idempotent design over all three rates: {viol} violations across {tot:,} duplicated deliveries.", ""])

# exp4
rs = rows("exp4_pods.jsonl")
if rs:
    out.extend(["## Experiment 4: pod assembly against the exact optimum", "",
                f"File `results/exp4_pods.jsonl`. Machine: {machine(rs[0])}. Single-threaded, one warm-up pass then one timed pass. Gap = 1 - value/exact, over breaks where the exact solver proved optimality.", "",
                "| Workload | Separation | Breaks proved | Mean candidates | Solver | Mean gap | Max gap | Optimal share | Solve p50 us | Solve p99 us | Invalid pods |",
                "|---|---|---|---|---|---|---|---|---|---|---|"])
    for o in rs:
        for s in o['solvers']:
            g = f"{s['mean_gap_pct']:.2f}%" if 'mean_gap_pct' in s else "-"
            mg = f"{s['max_gap_pct']:.1f}%" if 'max_gap_pct' in s else "-"
            osh = f"{s['optimal_share']:.3f}" if 'optimal_share' in s else "-"
            out.append(f"| {o['workload']} | {o['separation']} | {o['breaks_proved_optimal']:,} | {o['mean_candidates']:.1f} | {s['solver']} | {g} | {mg} | {osh} | {s['solve_p50_us']} | {s['solve_p99_us']} | {s['invalid_pods']} |")
    out.append("")

# exp5
rs = rows("exp5_shedding.jsonl")
if rs:
    out.extend(["## Experiment 5: priority shedding under sustained overload", "",
                f"File `results/exp5_shedding.jsonl`. Machine: {machine(rs[0])}. Sustained open-loop load, {rs[0]['seconds']} s per run, {rs[0]['live_share']*100:.0f}% LIVE, capacity set to {rs[0]['measured_capacity_per_s']:,.0f}/s.", "",
                "| Server | x capacity | Offered /s | Repeat | LIVE ok | LIVE shed | LIVE p99 ms | VOD ok | VOD shed rate | VOD errors | VOD p99 ms |",
                "|---|---|---|---|---|---|---|---|---|---|---|"])
    for o in rs:
        L, V = o['live'], o['vod']
        verr = V['unavailable'] + V['deadline_exceeded'] + V['other_errors']
        out.append(f"| {o['label']} | {o['multiple_of_capacity']:.1f} | {o['offered_per_s']:,.0f} | {o['repeat']} | {L['ok']:,} | {L['shed']:,} | {L['p99_ms']:.2f} | {V['ok']:,} | {V['shed_rate']:.3f} | {verr:,} | {V['p99_ms']:.2f} |")
    out.append("")

burst_table("exp6_dependency.jsonl", "Experiment 6: each dependency stopped in turn",
            "The same 8,000-request burst with Postgres, Kafka or Redis stopped, in each cap mode, and the legacy sync-write mode with Postgres stopped.")

# exp7
rs = rows("exp7_billing.jsonl")
if rs:
    out.extend(["## Experiment 7: billing pipeline end to end, with audit", "",
                f"File `results/exp7_billing.jsonl`. Machine: {machine(rs[0])}. AdServe, the beacon consumer and the Flink billing job running together; simulated players on the first 5,000 real ad breaks; beacons lost 1%, misrouted 2%.", "",
                "| Duplicate prob | Impressions served | With an IMPRESSION beacon | Beacons sent | Duplicates sent | Billing rows | Duplicate rows | Missing | Billed without beacon | Rerouted rows | Campaigns agreeing with Redis |",
                "|---|---|---|---|---|---|---|---|---|---|---|"])
    for o in rs:
        ag = o.get('audit_agreement')
        out.append(f"| {o['duplicate_probability']:.2f} | {o['impressions_served']:,} | {o['impressions_with_impression_beacon']:,} | {o['beacons_sent']:,} | {o['duplicate_beacons_sent']:,} | {o['billing_rows']:,} | {o['billing_duplicate_rows']} | {o['missing_from_billing']} | {o['billed_without_beacon']} | {o['billing_rerouted_rows']} | {o['audit_campaigns_agree']} of {o['audit_campaigns_agree']+o['audit_campaigns_disagree']} |")
    out.append("")

# exp8
rs = rows("exp8_hollow.jsonl")
if rs:
    out.extend(["## Experiment 8: campaign snapshot over Hollow", "", f"File `results/exp8_hollow.jsonl`. Machine: {machine(rs[0])}. {rs[0]['note']}.", "",
                "| Campaigns | Snapshot blob | Delta, one campaign changed | Publish to rebuilt, p50 | max |", "|---|---|---|---|---|"])
    for o in rs:
        out.append(f"| {o['campaigns']:,} | {o['snapshot_blob_bytes']:,} B | {o['mean_delta_blob_bytes_one_campaign_changed']:,} B | {o['publish_to_consumer_rebuilt_ms_p50']} ms | {o['publish_to_consumer_rebuilt_ms_max']} ms |")
    out.append("")

burst_table("exp9_runtime.jsonl", "Experiment 9: garbage collector and thread model",
            "The same bursts under generational ZGC with a virtual thread per request (default), G1 with virtual threads, and generational ZGC with 64 platform threads.")

# JMH
p = os.path.join(R, "jmh-hotpath.json")
if os.path.exists(p):
    js = json.load(open(p))
    out.extend(["## JMH: method-level cost of the decision path", "", "File `results/jmh-hotpath.json`. One fork, 3 warm-up and 5 measured iterations, average time per call.", "",
                "| Benchmark | ns per call | error (99.9%) |", "|---|---|---|"])
    for b in js:
        m = b["primaryMetric"]
        out.append(f"| {b['benchmark'].split('.')[-1]} | {m['score']:,.0f} | {m['scoreError']:,.0f} |")
    out.append("")

# M1
rs = rows("m1_replay.jsonl")
if rs:
    o = rs[-1]
    out.extend(["## Milestone 1: end-to-end replay check", "", f"File `results/m1_replay.jsonl` (last row). {o['traffic']}. {o['vod']['ok']:,} decided, {o.get('unique_request_ids','?'):,} distinct request ids, {o['decision_records_on_kafka']:,} decision records found on `ad.responses`.", ""])

open("NUMBERS_LEDGER.md", "w").write("\n".join(out) + "\n")
print("NUMBERS_LEDGER.md written")
